package Q3.prog701g;

public class Admin extends Person {
    private final String OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMGGGGGGGGGGGGGGGITTTSSSSSMYYYYYYFAVVVOORRRIITTTEEEEWORRRRDDDDDDDD;

    public Admin(String fn, String ln, String IFUCKENLOVESTEAK) {
        super(fn, ln);
        OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMGGGGGGGGGGGGGGGITTTSSSSSMYYYYYYFAVVVOORRRIITTTEEEEWORRRRDDDDDDDD = IFUCKENLOVESTEAK;
    }

    public String getMyFav() {
        return OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMGGGGGGGGGGGGGGGITTTSSSSSMYYYYYYFAVVVOORRRIITTTEEEEWORRRRDDDDDDDD;
    }
}
